// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"bitbucket.org/nugrahafajar37/fajar-rgb-golang-test/common/guard"
	"bitbucket.org/nugrahafajar37/fajar-rgb-golang-test/common/jwt"
	gift3 "bitbucket.org/nugrahafajar37/fajar-rgb-golang-test/controller/gift"
	"bitbucket.org/nugrahafajar37/fajar-rgb-golang-test/controller/root"
	user3 "bitbucket.org/nugrahafajar37/fajar-rgb-golang-test/controller/user"
	"bitbucket.org/nugrahafajar37/fajar-rgb-golang-test/database"
	"bitbucket.org/nugrahafajar37/fajar-rgb-golang-test/repository/gift"
	"bitbucket.org/nugrahafajar37/fajar-rgb-golang-test/repository/rating"
	"bitbucket.org/nugrahafajar37/fajar-rgb-golang-test/repository/redeem"
	"bitbucket.org/nugrahafajar37/fajar-rgb-golang-test/repository/role"
	"bitbucket.org/nugrahafajar37/fajar-rgb-golang-test/repository/user"
	"bitbucket.org/nugrahafajar37/fajar-rgb-golang-test/service/auth"
	gift2 "bitbucket.org/nugrahafajar37/fajar-rgb-golang-test/service/gift"
	user2 "bitbucket.org/nugrahafajar37/fajar-rgb-golang-test/service/user"
	"github.com/google/wire"
)

// Injectors from app.dependency.go:

func InitializeApp() *App {
	jwtHelper := jwt.NewJwtNelper()
	db := database.NewDB()
	roleImplRepository := role.NewRoleRepository(db)
	userImplRepository := user.NewUserRepository(db)
	authImplService := auth.NewAuthService(jwtHelper, userImplRepository)
	rootController := root.NewRootController(authImplService)
	userImplService := user2.NewUserService(userImplRepository)
	userController := user3.NewUserController(userImplService)
	giftImplRepository := gift.NewGiftRepository(db)
	ratingImplRepository := rating.NewRatingRepository(db)
	redeemImplRepository := redeem.NewRedeemRepository(db)
	giftImplService := gift2.NewGiftService(userImplRepository, giftImplRepository, ratingImplRepository, redeemImplRepository)
	giftController := gift3.NewGiftController(giftImplService)
	app := NewApp(jwtHelper, roleImplRepository, rootController, userController, giftController)
	return app
}

// app.dependency.go:

var WireSet = wire.NewSet(jwt.NewJwtNelper, role.NewRoleRepository, gift.NewGiftRepository, rating.NewRatingRepository, redeem.NewRedeemRepository, user.NewUserRepository, auth.NewAuthService, wire.Bind(new(auth.AuthRepository), new(*user.UserImplRepository)), wire.Bind(new(auth.JwtHelper), new(*jwt.JwtHelper)), gift2.NewGiftService, wire.Bind(new(gift2.GiftRepository), new(*gift.GiftImplRepository)), wire.Bind(new(gift2.RatingRepository), new(*rating.RatingImplRepository)), wire.Bind(new(gift2.RedeemRepository), new(*redeem.RedeemImplRepository)), wire.Bind(new(gift2.UserRepository), new(*user.UserImplRepository)), user2.NewUserService, wire.Bind(new(user2.UserRepository), new(*user.UserImplRepository)), gift3.NewGiftController, wire.Bind(new(gift3.GiftService), new(*gift2.GiftImplService)), root.NewRootController, wire.Bind(new(root.AuthService), new(*auth.AuthImplService)), user3.NewUserController, wire.Bind(new(user3.UserService), new(*user2.UserImplService)), wire.Bind(new(guard.AuthHelper), new(*jwt.JwtHelper)), wire.Bind(new(guard.RoleRepository), new(*role.RoleImplRepository)))
